# Generated by Django 5.1.6 on 2025-02-26 17:57

import accounts.validators
import django.db.models.deletion
import django.utils.timezone
import phone_field.models
import pyotp
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('address', models.CharField(blank=True, max_length=190, verbose_name='Endereço')),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Estado')),
                ('city', models.CharField(blank=True, max_length=190, verbose_name='Cidade')),
                ('cpf', models.CharField(default=0, max_length=11, validators=[accounts.validators.validate_cpf])),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('img', models.ImageField(blank=True, null=True, upload_to='user')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('situation', models.BooleanField(blank=True, default=False, verbose_name='Situação financeira')),
                ('perfil', models.BooleanField(blank=True, default=False, verbose_name='Perfil do Investidor')),
                ('two_factor', models.BooleanField(blank=True, default=False, verbose_name='Autenticação de dois fatores')),
                ('auth_provider', models.CharField(default='email', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OneTimePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TwoFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=pyotp.random_base32, max_length=100)),
                ('qr_code', models.ImageField(blank=True, help_text='Autenticação de 2 Fatores', null=True, upload_to='TwoFactor/qr_code')),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
