# Generated by Django 3.2.25 on 2024-04-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='perfil',
            field=models.BooleanField(blank=True, default=False, verbose_name='Perfil do Investidor'),
        ),
        migrations.AddField(
            model_name='user',
            name='situation',
            field=models.BooleanField(blank=True, default=False, verbose_name='Situação financeira'),
        ),
    ]
