# Generated by Django 3.2.25 on 2024-04-16 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20240416_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicao', models.CharField(choices=[('investidor', 'Investidor'), ('equilibrado', 'Equilibrado'), ('endividado', 'Endividado')], default='Conservador', max_length=190)),
                ('description', models.TextField()),
                ('minimum', models.IntegerField()),
                ('maximum', models.IntegerField()),
                ('usuario', models.ManyToManyField(blank=True, related_name='situacao_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.CharField(max_length=190, primary_key=True, serialize=False, unique=True)),
                ('investor', models.CharField(blank=True, choices=[('conservador', 'Conservador'), ('moderado', 'Moderado'), ('dinâmico', 'Dinâmico'), ('arrojado', 'Arrojado'), ('agressivo', 'Agressivo')], default='Conservador', max_length=190, null=True)),
                ('description', models.TextField()),
                ('risk_profile', models.CharField(max_length=150, null=True)),
                ('minimum', models.IntegerField()),
                ('maximum', models.IntegerField()),
                ('usuario', models.ManyToManyField(blank=True, related_name='perfil_investidor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
