# Generated by Django 3.2.25 on 2024-04-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_perfil_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('risk', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='situacao',
            name='description',
        ),
        migrations.AddField(
            model_name='situacao',
            name='goals',
            field=models.CharField(default=1, help_text='Objetivos Financeiros', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='situacao',
            name='horizon',
            field=models.CharField(default=1, help_text='Horizonte de Investimento', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='situacao',
            name='risk',
            field=models.CharField(default=1, help_text='Tolerância ao Risco', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='situacao',
            name='situation',
            field=models.CharField(default=1, help_text='Situação Financeira Atua', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='situacao',
            name='portfolio',
            field=models.ManyToManyField(help_text='Diversificação do Portfólio', to='accounts.Portfolio'),
        ),
    ]
