# Generated by Django 3.2.25 on 2024-04-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20240417_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='situacao',
            name='strategy',
            field=models.CharField(blank=True, help_text='Estratégia Financeira', max_length=400),
        ),
    ]
