# Generated by Django 3.2.25 on 2024-04-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_situacao_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situacao',
            name='goals',
            field=models.TextField(help_text='Objetivos Financeiros'),
        ),
        migrations.AlterField(
            model_name='situacao',
            name='horizon',
            field=models.TextField(help_text='Horizonte de Investimento'),
        ),
        migrations.AlterField(
            model_name='situacao',
            name='risk',
            field=models.TextField(help_text='Tolerância ao Risco'),
        ),
        migrations.AlterField(
            model_name='situacao',
            name='situation',
            field=models.TextField(help_text='Situação Financeira Atua'),
        ),
        migrations.AlterField(
            model_name='situacao',
            name='strategy',
            field=models.TextField(blank=True, help_text='Estratégia Financeira'),
        ),
    ]
