# Generated by Django 3.2.25 on 2024-04-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20240417_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situacao',
            name='portfolio',
            field=models.ManyToManyField(blank=True, help_text='Diversificação do Portfólio', to='accounts.Portfolio'),
        ),
    ]
