# Generated by Django 3.2.25 on 2024-04-18 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_perfil_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='color',
        ),
    ]
