# Generated by Django 3.2.25 on 2024-04-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_perfil_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='color',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
