# Generated by Django 3.2.25 on 2024-04-27 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_perfil_investor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='situacao',
            options={'ordering': ('id',), 'verbose_name': 'Situacao Financeira', 'verbose_name_plural': 'Situacoes Financeiras'},
        ),
        migrations.RemoveField(
            model_name='situacao',
            name='strategy',
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=0, null=True)),
                ('name', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.situacao', verbose_name='Situacao')),
            ],
            options={
                'verbose_name': 'Estratégia',
                'verbose_name_plural': 'Estratégias',
                'ordering': ('order',),
            },
        ),
    ]
