# Generated by Django 3.2.25 on 2024-04-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20240427_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='situacao',
            name='strategic',
            field=models.ManyToManyField(help_text='Estrategias', related_name='estrategicas', to='accounts.Strategy'),
        ),
    ]
