# Generated by Django 5.1.6 on 2025-05-12 19:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('ticker', models.CharField(max_length=10, unique=True, verbose_name='Ticker')),
                ('tipo_ativo', models.CharField(choices=[('acao', 'Ação'), ('titulo', 'Título'), ('fundo', 'Fundo'), ('cripto', 'Criptomoeda'), ('outro', 'Outro')], max_length=50, verbose_name='Tipo de Ativo')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Preço')),
                ('volatilidade', models.FloatField(help_text='Volatilidade anualizada (ex.: 0.2 para 20%)', verbose_name='Volatilidade')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
                'indexes': [models.Index(fields=['ticker'], name='agents_asse_ticker_01dd2a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Total')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Carteira',
                'verbose_name_plural': 'Carteiras',
            },
        ),
        migrations.CreateModel(
            name='InvestmentAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('modelo_langchain', models.CharField(default='gpt-4', help_text='Modelo de linguagem usado pelo LangChain', max_length=100, verbose_name='Modelo LangChain')),
                ('estrategia', models.CharField(choices=[('aversao_risco', 'Aversão ao Risco'), ('equilibrado', 'Equilibrado'), ('crescimento', 'Crescimento')], max_length=50, verbose_name='Estratégia')),
                ('configuracao', models.JSONField(default=dict, help_text='Configuração do agente LangChain', verbose_name='Configuração')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.portfolio', verbose_name='Carteira')),
            ],
            options={
                'verbose_name': 'Agente de Investimento',
                'verbose_name_plural': 'Agentes de Investimento',
            },
        ),
        migrations.CreateModel(
            name='AdvisorRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto_recomendacao', models.TextField(verbose_name='Texto da Recomendação')),
                ('avaliacao_risco', models.JSONField(default=dict, help_text='Detalhes da análise de risco', verbose_name='Avaliação de Risco')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('ativos_recomendados', models.ManyToManyField(blank=True, to='agents.asset', verbose_name='Ativos Recomendados')),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.investmentagent', verbose_name='Agente')),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.portfolio', verbose_name='Carteira')),
            ],
            options={
                'verbose_name': 'Recomendação do Consultor',
                'verbose_name_plural': 'Recomendações do Consultor',
            },
        ),
        migrations.CreateModel(
            name='RiskProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nivel_risco', models.CharField(choices=[('conservador', 'Conservador'), ('moderado', 'Moderado'), ('agressivo', 'Agressivo')], max_length=20, verbose_name='Nível de Risco')),
                ('tolerancia_perda_maxima', models.FloatField(help_text='Tolerância máxima de perda percentual (ex.: 0.1 para 10%)', verbose_name='Tolerância Máxima de Perda')),
                ('horizonte_investimento', models.IntegerField(help_text='Horizonte de investimento em anos', verbose_name='Horizonte de Investimento')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Risco',
                'verbose_name_plural': 'Perfis de Risco',
            },
        ),
        migrations.AddField(
            model_name='portfolio',
            name='perfil_risco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.riskprofile', verbose_name='Perfil de Risco'),
        ),
        migrations.CreateModel(
            name='PortfolioAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Quantidade')),
                ('percentual_alocacao', models.FloatField(help_text='Percentual da carteira (ex.: 0.25 para 25%)', verbose_name='Percentual de Alocação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.asset', verbose_name='Ativo')),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='agents.portfolio', verbose_name='Carteira')),
            ],
            options={
                'verbose_name': 'Alocação de Carteira',
                'verbose_name_plural': 'Alocações de Carteira',
                'constraints': [models.CheckConstraint(condition=models.Q(('percentual_alocacao__gte', 0.0), ('percentual_alocacao__lte', 1.0)), name='percentual_alocacao_valido')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_transacao', models.CharField(choices=[('compra', 'Compra'), ('venda', 'Venda')], max_length=20, verbose_name='Tipo de Transação')),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Quantidade')),
                ('preco_por_unidade', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Preço por Unidade')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total')),
                ('executado_em', models.DateTimeField(verbose_name='Executado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.asset', verbose_name='Ativo')),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='agents.portfolio', verbose_name='Carteira')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'indexes': [models.Index(fields=['carteira', 'executado_em'], name='agents_tran_carteir_e4ceef_idx')],
            },
        ),
    ]
