# Generated by Django 5.1.6 on 2025-05-12 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='portfolioallocation',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='investmentagent',
            name='carteira',
        ),
        migrations.RemoveField(
            model_name='investmentagent',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='perfil_risco',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='carteira',
        ),
        migrations.RemoveField(
            model_name='portfolioallocation',
            name='carteira',
        ),
        migrations.RemoveField(
            model_name='riskprofile',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='AdvisorRecommendation',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='InvestmentAgent',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='PortfolioAllocation',
        ),
        migrations.DeleteModel(
            name='RiskProfile',
        ),
    ]
