# Generated by Django 5.1.6 on 2025-05-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('ação', 'Ação'), ('título', 'Título'), ('fundo', 'Fundo'), ('cripto', 'Criptomoeda'), ('outro', 'Outro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='investmentagent',
            name='strategy',
            field=models.CharField(choices=[('avesso ao risco', 'Averso ao risco'), ('equilibrado', 'Equilibrado'), ('crescimento', 'Crescimento')], max_length=50),
        ),
        migrations.AlterField(
            model_name='riskprofile',
            name='risk_level',
            field=models.CharField(choices=[('conservador', 'Conservador'), ('moderado', 'Moderado'), ('agressivo', 'Agressivo')], max_length=20),
        ),
    ]
