# Generated by Django 5.1.6 on 2025-05-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_alter_asset_asset_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('ação', 'Ação'), ('título', 'Título'), ('fundo', 'Fundo'), ('cripto', 'Criptomoeda'), ('commodities', 'Commodities'), ('moeda', 'Moeda'), ('imóvel', 'Imóvel'), ('index', 'Índice'), ('renda fixa', 'Renda Fixa'), ('renda variável', 'Renda Variável'), ('opção', 'Opção'), ('futuro', 'Futuro'), ('swap', 'Swap'), ('forex', 'Forex'), ('etf', 'ETF'), ('bdr', 'BDR'), ('fii', 'FII'), ('debênture', 'Debênture'), ('cdb', 'CDB'), ('lci', 'LCI'), ('lca', 'LCA'), ('tesouro direto', 'Tesouro Direto'), ('previdência', 'Previdência'), ('poupança', 'Poupança'), ('fundos imobiliários', 'Fundos Imobiliários'), ('ações preferenciais', 'Ações Preferenciais'), ('ações ordinárias', 'Ações Ordinárias'), ('ações de dividendos', 'Ações de Dividendos'), ('ações de crescimento', 'Ações de Crescimento'), ('ações de baixo risco', 'Ações de Baixo Risco'), ('ações de alto risco', 'Ações de Alto Risco'), ('outro', 'Outro')], max_length=50),
        ),
    ]
