# Generated by Django 5.1.6 on 2025-05-12 22:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_investmentagent_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentagent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentagent',
            name='portfolios',
            field=models.ManyToManyField(blank=True, related_name='investment_agents', to='agents.portfolio'),
        ),
        migrations.AlterField(
            model_name='investmentagent',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='investment_agents', to=settings.AUTH_USER_MODEL),
        ),
    ]
