# Generated by Django 5.1.6 on 2025-05-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_rename_image_investmentagent_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentagent',
            name='experience',
            field=models.IntegerField(default=0, help_text='Experience in years'),
        ),
        migrations.AddField(
            model_name='investmentagent',
            name='rating',
            field=models.FloatField(blank=True, default=0.0, help_text='Rating from 0 to 5', null=True),
        ),
        migrations.AddField(
            model_name='investmentagent',
            name='reviews',
            field=models.IntegerField(default=0, help_text='Number of reviews received'),
        ),
    ]
