# Generated by Django 5.1.6 on 2025-05-13 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_investmentagent_experience_investmentagent_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentagent',
            old_name='asset',
            new_name='specialty',
        ),
    ]
