# Generated by Django 5.1.6 on 2025-05-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0014_rename_asset_investmentagent_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentagent',
            name='model',
            field=models.CharField(choices=[('robo', 'Robo'), ('humano', 'Humano'), ('híbrido', 'Híbrido')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investmentagent',
            name='type',
            field=models.CharField(choices=[('consultor', 'Consultor'), ('gestor', 'Gestor'), ('analista', 'Analista'), ('especialista', 'Especialista')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
