# Generated by Django 5.1.6 on 2025-05-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0015_investmentagent_model_investmentagent_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentagent',
            name='type',
        ),
        migrations.AlterField(
            model_name='investmentagent',
            name='specialty',
            field=models.CharField(choices=[('consultor', 'Consultor'), ('gestor', 'Gestor'), ('analista', 'Analista'), ('especialista', 'Especialista')], max_length=100),
        ),
    ]
