# Generated by Django 5.1.6 on 2025-05-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0016_remove_investmentagent_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentagent',
            name='langchain_tool',
            field=models.CharField(choices=[('chat', 'Chat'), ('llm', 'LLM'), ('retriever', 'Retriever'), ('qa', 'QA'), ('agent', 'Agent'), ('tool', 'Tool')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investmentagent',
            name='langchain_model',
            field=models.CharField(choices=[('gpt-4', 'GPT-4'), ('gemini', 'Gemini'), ('llama-2', 'Llama 2'), ('claude', 'Claude'), ('mistral', 'Mistral'), ('qwen', 'Qwen'), ('deepSpeeker', 'DeepSpeeker'), ('grok', 'Grok')], default='gpt-3.5-turbo', max_length=100),
        ),
    ]
