# Generated by Django 5.1.6 on 2025-05-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0017_investmentagent_langchain_tool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentagent',
            name='asset',
            field=models.CharField(choices=[('ação', 'Ação'), ('título', 'Título'), ('fundo', 'Fundo'), ('cripto', 'Criptomoeda'), ('commodities', 'Commodities'), ('moeda', 'Moeda'), ('index', 'Índice'), ('opção', 'Opção'), ('etf', 'ETF'), ('bdr', 'BDR'), ('fii', 'FII'), ('debênture', 'Debênture'), ('cdb', 'CDB'), ('lci', 'LCI'), ('lca', 'LCA'), ('tesouro direto', 'Tesouro Direto'), ('fundos imobiliários', 'Fundos Imobiliários')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
