# Generated by Django 5.1.6 on 2025-05-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0018_investmentagent_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentagent',
            name='asset',
            field=models.CharField(choices=[('ação', 'Ação'), ('título', 'Título'), ('fundo', 'Fundo'), ('cripto', 'Criptomoeda'), ('commodities', 'Commodities'), ('moeda', 'Moeda'), ('index', 'Índice'), ('opção', 'Opção'), ('etf', 'ETF'), ('bdr', 'BDR'), ('fii', 'FII'), ('debênture', 'Debênture'), ('cdb', 'CDB'), ('lci', 'LCI'), ('lca', 'LCA'), ('tesouro direto', 'Tesouro Direto'), ('fundos imobiliários', 'Fundos Imobiliários'), ('gestor de patrimônio', 'Gestor de patrimônio'), ('gestor de investimentos', 'Gestor de investimentos'), ('gestor de risco', 'Gestor de risco')], max_length=100),
        ),
    ]
