# Generated by Django 5.1.6 on 2025-05-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0019_alter_investmentagent_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentagent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='investmentagent',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='LangChain agent configuration', null=True),
        ),
    ]
