# Generated by Django 2.2 on 2022-03-29 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.CharField(help_text='codigo identificador da apis na plataforma', max_length=150, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(help_text='Nome da plataforma da api', max_length=150, unique=True)),
                ('descricao', models.TextField(help_text='Descricao da plataforma da api')),
                ('status', models.CharField(choices=[('gratis', 'Gratis'), ('paga', 'Paga')], default='gratis', help_text='Status da api', max_length=9)),
                ('image', models.ImageField(upload_to='api')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Data da criação da api')),
                ('api_key', models.CharField(help_text='Chave de acesso da apis do usuário', max_length=400, unique=True)),
                ('secret_key', models.CharField(help_text='Chave secreta de acesso da api do usuário', max_length=400, unique=True)),
                ('qr_code', models.ImageField(blank=True, help_text='QR code de autorização do veiculo', upload_to='Veiculo/qr_code')),
                ('is_active', models.BooleanField(blank=True, default=False, verbose_name='Está ativo?')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API',
                'verbose_name_plural': 'APIs',
                'ordering': ['nome'],
            },
        ),
    ]
