# Generated by Django 5.1.6 on 2025-03-20 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_account_broker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broker',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='broker',
            old_name='nome',
            new_name='name',
        ),
    ]
