# Generated by Django 5.1.6 on 2025-03-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_rename_img_broker_image_rename_nome_broker_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt5api',
            name='account',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mt5api',
            name='image',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
