# Generated by Django 5.1.6 on 2025-03-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_mt5api_account_mt5api_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mt5api',
            name='login',
            field=models.IntegerField(max_length=255, unique=True),
        ),
    ]
