# Generated by Django 5.1.6 on 2025-03-23 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_alter_mt5api_login'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mt5api',
            options={'verbose_name': 'MT5 API', 'verbose_name_plural': 'MT5 APIs'},
        ),
        migrations.AddField(
            model_name='mt5api',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
