# Generated by Django 5.1.6 on 2025-03-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_alter_mt5api_options_mt5api_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mt5api',
            old_name='broker_name',
            new_name='broker',
        ),
        migrations.AddField(
            model_name='mt5api',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mt5api',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
