# Generated by Django 5.1.6 on 2025-03-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_rename_broker_name_mt5api_broker_mt5api_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mt5api',
            name='password',
        ),
    ]
