# Generated by Django 5.1.6 on 2025-03-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_remove_mt5api_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mt5api',
            name='login',
            field=models.CharField(max_length=255),
        ),
    ]
