# Generated by Django 5.1.6 on 2025-03-23 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_alter_mt5api_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mt5api',
            old_name='login',
            new_name='password',
        ),
    ]
