# Generated by Django 4.1.3 on 2023-05-12 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacoes', models.FloatField()),
                ('loss', models.FloatField()),
                ('profit', models.FloatField()),
                ('total', models.FloatField()),
            ],
            options={
                'verbose_name': 'Capital',
                'verbose_name_plural': 'Capitais',
                'ordering': ['total'],
            },
        ),
        migrations.CreateModel(
            name='Operacoe',
            fields=[
                ('id', models.IntegerField(help_text='Numero indentificação da operação', primary_key=True, serialize=False)),
                ('ativo', models.CharField(help_text='O nome do ativo ', max_length=150)),
                ('stoploss', models.BooleanField(help_text='Stop Loss')),
                ('takeprofit', models.BooleanField(help_text='Take Profit')),
                ('inicio', models.DateTimeField(auto_now_add=True, help_text='Data da entreda da operação')),
                ('tipo', models.CharField(choices=[('compra', 'Compra'), ('venda', 'venda')], default='compra', help_text='Tipo de operação', max_length=150)),
                ('volume', models.FloatField()),
                ('entrada', models.FloatField()),
                ('sl', models.FloatField()),
                ('tp', models.FloatField()),
                ('saida', models.FloatField()),
                ('lucro', models.FloatField()),
            ],
            options={
                'verbose_name': 'Operação',
                'verbose_name_plural': 'Operações',
                'ordering': ['inicio'],
            },
        ),
        migrations.CreateModel(
            name='Gerenciamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('indice', 'Indice'), ('dolar', 'Dolar'), ('ações', 'Ações'), ('opções', 'Opções'), ('americano', 'Americano')], default='indice', max_length=150)),
                ('inicial', models.DecimalField(decimal_places=2, help_text='O valor inicial para operações', max_digits=10)),
                ('preco', models.DecimalField(decimal_places=2, help_text='O Preço do contrato', max_digits=10)),
                ('porcent', models.DecimalField(decimal_places=2, help_text='A Porcentagem de perca por operações', max_digits=10)),
                ('ganho', models.DecimalField(decimal_places=2, help_text='O Valor do ganho', max_digits=10)),
                ('pontos', models.IntegerField()),
                ('contratos', models.IntegerField()),
                ('perda', models.IntegerField()),
                ('stop', models.FloatField()),
                ('capital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_gerencimento', to='trading.capital')),
            ],
            options={
                'verbose_name': 'Gerenciamento',
                'verbose_name_plural': 'Gerenciamentos',
                'ordering': ['inicial'],
            },
        ),
    ]
