# Generated by Django 4.0.5 on 2022-11-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.CharField(max_length=190, primary_key=True, serialize=False, unique=True)),
                ('investor', models.CharField(choices=[('cconservador', 'Conservador'), ('moderado', 'Moderado'), ('dinâmico', 'Dinâmico'), ('arrojado', 'Arrojado'), ('Agressivo', 'Agressivo')], default='Conservador', max_length=190)),
                ('description', models.TextField()),
                ('risk_profile', models.CharField(max_length=150)),
                ('minimum', models.IntegerField()),
                ('maximum', models.IntegerField()),
            ],
        ),
    ]
