# Generated by Django 4.0.5 on 2022-11-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.CharField(max_length=190, primary_key=True, serialize=False, unique=True)),
                ('situacao', models.CharField(choices=[('investidor', 'Investidor'), ('equilibrado', 'Equilibrado'), ('endividade', 'Endividado')], default='Conservador', max_length=190)),
                ('description', models.TextField()),
                ('minimum', models.IntegerField()),
                ('maximum', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='perfil',
            name='investor',
            field=models.CharField(choices=[('conservador', 'Conservador'), ('moderado', 'Moderado'), ('dinâmico', 'Dinâmico'), ('arrojado', 'Arrojado'), ('Agressivo', 'Agressivo')], default='Conservador', max_length=190),
        ),
    ]
