# Generated by Django 4.0.5 on 2022-11-10 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investor', '0002_situacao_alter_perfil_investor'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='usuarios',
            field=models.ManyToManyField(related_name='perfil_investidor', to=settings.AUTH_USER_MODEL),
        ),
    ]
