# Generated by Django 4.0.5 on 2022-11-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0003_perfil_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='investor',
            field=models.CharField(choices=[('conservador', 'Conservador'), ('moderado', 'Moderado'), ('dinâmico', 'Dinâmico'), ('arrojado', 'Arrojado'), ('agressivo', 'Agressivo')], default='Conservador', max_length=190),
        ),
    ]
