# Generated by Django 4.0.5 on 2022-11-10 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0004_alter_perfil_investor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='situacao',
            old_name='situacao',
            new_name='condicao',
        ),
    ]
