# Generated by Django 4.0.5 on 2022-11-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0005_rename_situacao_situacao_condicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situacao',
            name='condicao',
            field=models.CharField(choices=[('investidor', 'Investidor'), ('equilibrado', 'Equilibrado'), ('endividado', 'Endividado')], default='Conservador', max_length=190),
        ),
    ]
