# Generated by Django 5.1.6 on 2025-05-15 20:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Ativo')),
                ('ticker', models.CharField(max_length=20, unique=True, verbose_name='Ticker')),
                ('asset_type', models.CharField(choices=[('STOCK', 'Ação'), ('COMMODITY', 'Commodity'), ('CRYPTO', 'Criptomoeda'), ('CURRENCY', 'Moeda (Forex)'), ('INDEX', 'Índice'), ('BOND', 'Título'), ('FUND', 'Fundo'), ('ETF', 'ETF')], max_length=50, verbose_name='Tipo de Ativo')),
                ('currency', models.CharField(choices=[('USD', 'Dólar Americano'), ('BRL', 'Real Brasileiro'), ('EUR', 'Euro'), ('JPY', 'Iene Japonês'), ('GBP', 'Libra Esterlina'), ('OTHER', 'Outra')], default='BRL', max_length=5, verbose_name='Moeda')),
                ('sector', models.CharField(blank=True, help_text='Setor do ativo (ex.: Tecnologia, Energia, Financeiro), aplicável para Ações e ETFs', max_length=100, verbose_name='Setor')),
                ('volatility', models.DecimalField(decimal_places=2, help_text='Volatilidade histórica do ativo em percentual', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Volatilidade (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
            },
        ),
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Perfil')),
                ('risk_tolerance', models.CharField(choices=[('CONSERVATIVE', 'Conservador'), ('MODERATE', 'Moderado'), ('AGGRESSIVE', 'Agressivo')], max_length=20, verbose_name='Tolerância ao Risco')),
                ('max_exposure', models.DecimalField(decimal_places=2, help_text='Percentual máximo do portfólio para um único ativo', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Exposição Máxima (%)')),
                ('fixed_income_allocation', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Alocação em Renda Fixa (%)')),
                ('variable_income_allocation', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Alocação em Renda Variável (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Perfil de Investidor',
                'verbose_name_plural': 'Perfis de Investidor',
            },
        ),
        migrations.CreateModel(
            name='Investidor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('renda_mensal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Renda Mensal')),
                ('despesas_mensais', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Despesas Mensais')),
                ('dividas', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dívidas')),
                ('investimentos', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Investimentos')),
                ('reserva_emergencia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Reserva de Emergência')),
                ('tolerancia_risco', models.IntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta')], default=1, verbose_name='Tolerância ao Risco')),
                ('horizonte_tempo', models.IntegerField(choices=[(1, 'Curto prazo'), (2, 'Médio prazo'), (3, 'Longo prazo')], default=1, verbose_name='Horizonte de Tempo')),
                ('objetivo', models.CharField(choices=[('seguranca', 'Segurança'), ('crescimento', 'Crescimento'), ('especulacao', 'Especulação')], default='seguranca', max_length=50, verbose_name='Objetivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investidor', to=settings.AUTH_USER_MODEL)),
                ('investor_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.investorprofile', verbose_name='Perfil de Investidor')),
            ],
            options={
                'verbose_name': 'Investidor',
                'verbose_name_plural': 'Investidores',
            },
        ),
        migrations.CreateModel(
            name='InvestmentOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venda')], max_length=20, verbose_name='Tipo de Operação')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Preço Unitário')),
                ('operation_date', models.DateTimeField(verbose_name='Data da Operação')),
                ('total_value', models.DecimalField(decimal_places=2, editable=False, max_digits=15, verbose_name='Valor Total')),
                ('risk_score', models.DecimalField(decimal_places=2, help_text='Pontuação de risco calculada para a operação', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pontuação de Risco')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.asset', verbose_name='Ativo')),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.investidor', verbose_name='Investidor')),
            ],
            options={
                'verbose_name': 'Operação de Investimento',
                'verbose_name_plural': 'Operações de Investimento',
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_type', models.CharField(choices=[('MARKET', 'Risco de Mercado'), ('CREDIT', 'Risco de Crédito'), ('LIQUIDITY', 'Risco de Liquidez'), ('OPERATIONAL', 'Risco Operacional'), ('CURRENCY', 'Risco Cambial'), ('COMMODITY', 'Risco de Commodity')], max_length=50, verbose_name='Tipo de Risco')),
                ('risk_level', models.CharField(choices=[('LOW', 'Baixo'), ('MEDIUM', 'Médio'), ('HIGH', 'Alto')], max_length=20, verbose_name='Nível de Risco')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('assessment_date', models.DateTimeField(auto_now_add=True, verbose_name='Data da Avaliação')),
                ('mitigation_strategy', models.TextField(blank=True, verbose_name='Estratégia de Mitigação')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.investmentoperation', verbose_name='Operação')),
            ],
            options={
                'verbose_name': 'Avaliação de Risco',
                'verbose_name_plural': 'Avaliações de Risco',
            },
        ),
    ]
