# Generated by Django 3.2.25 on 2024-04-27 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('risk', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicao', models.CharField(choices=[('investidor', 'Investidor'), ('equilibrado', 'Equilibrado'), ('endividado', 'Endividado')], default='Conservador', max_length=190)),
                ('goals', models.TextField(help_text='Objetivos Financeiros')),
                ('situation', models.TextField(help_text='Situação Financeira Atua')),
                ('risk', models.TextField(help_text='Tolerância ao Risco')),
                ('horizon', models.TextField(help_text='Horizonte de Investimento')),
                ('minimum', models.IntegerField()),
                ('maximum', models.IntegerField()),
                ('portfolio', models.ManyToManyField(blank=True, help_text='Diversificação do Portfólio', to='management.Portfolio')),
            ],
            options={
                'verbose_name': 'Situacao Financeira',
                'verbose_name_plural': 'Situacoes Financeiras',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=0, null=True)),
                ('name', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.situacao', verbose_name='Situacao')),
            ],
            options={
                'verbose_name': 'Estratégia',
                'verbose_name_plural': 'Estratégias',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='situacao',
            name='strategic',
            field=models.ManyToManyField(help_text='Estrategias', related_name='estrategicas', to='management.Strategy'),
        ),
        migrations.AddField(
            model_name='situacao',
            name='usuario',
            field=models.ManyToManyField(blank=True, related_name='situacao_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('investor', models.CharField(blank=True, choices=[('Conservador', 'Conservador'), ('Moderado', 'Moderado'), ('Dinâmico', 'Dinâmico'), ('Arrojado', 'Arrojado'), ('Agressivo', 'Agressivo')], default='Conservador', max_length=190, null=True)),
                ('description', models.TextField()),
                ('risk_profile', models.CharField(max_length=150, null=True)),
                ('minimum', models.IntegerField()),
                ('maximum', models.IntegerField()),
                ('color', models.CharField(max_length=40)),
                ('usuario', models.ManyToManyField(blank=True, related_name='perfil_investidor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Investidor',
                'verbose_name_plural': 'Perfis do Investidor',
                'ordering': ('id',),
            },
        ),
    ]
