# Generated by Django 5.1.6 on 2025-05-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='currency',
            field=models.CharField(choices=[('USD', 'Dólar Americano'), ('BRL', 'Real Brasileiro'), ('EUR', 'Euro'), ('JPY', 'Iene Japonês'), ('GBP', 'Libra Esterlina'), ('OTHER', 'Outra')], default='USD', max_length=5, verbose_name='Moeda'),
        ),
    ]
