# Generated by Django 3.2.25 on 2024-04-27 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situacao',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='situacao',
            name='horizon',
        ),
        migrations.RemoveField(
            model_name='situacao',
            name='risk',
        ),
        migrations.RemoveField(
            model_name='situacao',
            name='situation',
        ),
    ]
