# Generated by Django 5.1.6 on 2025-05-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_asset_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='img',
            field=models.ImageField(default=1, upload_to='asset/images', verbose_name='Imagem do Ativo'),
            preserve_default=False,
        ),
    ]
