# Generated by Django 3.2.25 on 2024-04-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20240427_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situacao',
            name='strategic',
            field=models.ManyToManyField(blank=True, help_text='Estrategias', related_name='estrategicas', to='management.Strategy'),
        ),
    ]
