# Generated by Django 3.2.25 on 2024-04-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_situacao_strategic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='risk_profile',
        ),
        migrations.RemoveField(
            model_name='situacao',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='situacao',
            name='strategic',
        ),
        migrations.AddField(
            model_name='perfil',
            name='strategic',
            field=models.ManyToManyField(blank=True, help_text='Estrategias', related_name='estrategicas', to='management.Strategy'),
        ),
    ]
