# Generated by Django 3.2.25 on 2024-04-27 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20240427_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.ManyToManyField(blank=True, help_text='Portfólio', related_name='portifolio_risk', to='management.Portfolio')),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='risk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to='management.risk'),
            preserve_default=False,
        ),
    ]
