# Generated by Django 3.2.25 on 2024-04-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20240427_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='risk',
        ),
        migrations.AddField(
            model_name='risk',
            name='alto',
            field=models.BooleanField(default=False, help_text='Risk Alto'),
        ),
        migrations.AddField(
            model_name='risk',
            name='baixo',
            field=models.BooleanField(default=False, help_text='Baixo Risk'),
        ),
        migrations.AddField(
            model_name='risk',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='risk',
            name='idade',
            field=models.CharField(default=1, max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='risk',
            name='maximum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='risk',
            name='minimum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='risk',
            name='moderado',
            field=models.BooleanField(default=False, help_text='Risk Moderado'),
        ),
    ]
