# Generated by Django 3.2.25 on 2024-04-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20240427_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='risk',
            options={'ordering': ('id',), 'verbose_name': 'Risco', 'verbose_name_plural': 'Riscos'},
        ),
        migrations.AlterField(
            model_name='perfil',
            name='maximum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='minimum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='situacao',
            name='maximum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='situacao',
            name='minimum',
            field=models.IntegerField(default=0),
        ),
    ]
