# Generated by Django 3.2.25 on 2024-04-27 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20240427_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='color',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='risk',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to='management.risk'),
        ),
    ]
