# Generated by Django 3.2.25 on 2024-04-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20240427_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='risk',
        ),
        migrations.AddField(
            model_name='perfil',
            name='risk',
            field=models.ManyToManyField(blank=True, related_name='risk_profile', to='management.Risk'),
        ),
    ]
