# Generated by Django 3.2.25 on 2024-04-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20240427_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('tipo', models.CharField(choices=[('Fixa', 'Fixa'), ('Variável', 'Variável')], default='Fixa', max_length=90)),
                ('tax', models.BooleanField(default=False, help_text='Imposto')),
            ],
        ),
        migrations.RemoveField(
            model_name='risk',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='risk',
            name='investimentos',
            field=models.ManyToManyField(blank=True, help_text='Portfólio', related_name='portifolio_risk', to='management.Investimento'),
        ),
    ]
