# Generated by Django 4.0.5 on 2022-10-21 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=28)),
                ('data', models.DateTimeField()),
                ('horario', models.CharField(max_length=19)),
                ('img', models.ImageField(blank=True, null=True, upload_to='bandeiras')),
                ('pais', models.CharField(max_length=19)),
                ('moeda', models.CharField(max_length=19)),
                ('importancia', models.CharField(max_length=19)),
                ('evento', models.TextField()),
                ('K', models.BooleanField(default=False)),
                ('M', models.BooleanField(default=False)),
                ('B', models.BooleanField(default=False)),
                ('percent', models.BooleanField(default=False)),
                ('actual', models.FloatField(max_length=19)),
                ('forecast', models.FloatField(max_length=19)),
                ('previous', models.FloatField(max_length=19)),
            ],
            options={
                'verbose_name': 'Evento Economico',
                'verbose_name_plural': 'Eventos Economico',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('region', models.CharField(help_text='O nome do Continente', max_length=150)),
                ('subregion', models.CharField(help_text='O nome do Continente', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Countrie',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='O nome do Pais', max_length=150)),
                ('official', models.CharField(help_text='Nome Oficial do país', max_length=400)),
                ('area', models.FloatField(default=0, help_text='A area do teritorial do pais')),
                ('borders', models.CharField(blank=True, help_text='Pais vizinhos', max_length=400, null=True)),
                ('capital', models.CharField(help_text='Capital do Pais ', max_length=400)),
                ('population', models.IntegerField(default=0)),
                ('coatOfArms', models.URLField()),
                ('languages', models.CharField(max_length=150)),
                ('flags', models.URLField()),
                ('continents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='continente', to='economia.continent')),
            ],
        ),
        migrations.CreateModel(
            name='Currencie',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='nome da moeda', max_length=50)),
                ('symbol', models.CharField(help_text='Simbolo da moeda', max_length=10)),
                ('paises', models.ManyToManyField(related_name='moedas_paises', to='economia.countrie')),
            ],
        ),
        migrations.AddField(
            model_name='countrie',
            name='currencies',
            field=models.ManyToManyField(to='economia.currencie'),
        ),
        migrations.AddField(
            model_name='continent',
            name='paises',
            field=models.ManyToManyField(related_name='paises', to='economia.countrie'),
        ),
    ]
