# Generated by Django 4.0.5 on 2022-10-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicators',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('pib', models.FloatField(default=0, help_text='Produto Interno Bruto (PIB)')),
                ('selic', models.FloatField(default=0, help_text='taxa básica de juros da economia')),
                ('ipca', models.FloatField(default=0, help_text='Índice Nacional de Preços ao Consumidor Amplo (IPCA)')),
                ('tr', models.FloatField(default=0, help_text='Taxa Referencial')),
            ],
        ),
    ]
