# Generated by Django 4.0.5 on 2022-10-27 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.CharField(max_length=190, primary_key=True, serialize=False, unique=True)),
                ('investor', models.CharField(choices=[('cconservador', 'Conservador'), ('moderado', 'Moderado'), ('dinâmico', 'Dinâmico'), ('arrojado', 'Arrojado'), ('Agressivo', 'Agressivo')], default='Conservador', max_length=190)),
                ('description', models.TextField()),
                ('risk_profile', models.CharField(max_length=150)),
                ('minimum', models.IntegerField()),
                ('maximum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.CharField(max_length=190, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='A Perguntas do questionario', max_length=400)),
            ],
            options={
                'verbose_name': 'Questionário',
                'verbose_name_plural': 'Questionários',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.CharField(max_length=190, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='Titulo do assunto do questionario', max_length=150)),
                ('description', models.TextField(help_text='Descrição do Assuntos do questionario')),
                ('created', models.DateTimeField()),
                ('percentage', models.IntegerField(default=0, help_text='A porcentagem do usuários')),
                ('total', models.IntegerField(default=0, help_text='O total de questionarios')),
                ('questionnaire', models.ManyToManyField(blank=True, related_name='subject_questionnaire', to='quiz.questionnaire')),
                ('usuario', models.ManyToManyField(blank=True, related_name='subject_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assunto',
                'verbose_name_plural': 'Assuntos',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.CharField(max_length=190, primary_key=True, serialize=False, unique=True)),
                ('answers', models.CharField(help_text='respostas', max_length=400)),
                ('correct', models.BooleanField()),
                ('valor', models.IntegerField()),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionario', to='quiz.questionnaire')),
                ('usuario', models.ManyToManyField(blank=True, related_name='questoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
            },
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='subject',
            field=models.ManyToManyField(related_name='questionario_assunto', to='quiz.subject'),
        ),
    ]
