# Generated by Django 4.0.5 on 2022-11-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersanswer',
            name='quiz_taker',
        ),
        migrations.AddField(
            model_name='usersanswer',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersanswer',
            name='date_finished',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usersanswer',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
