# Generated by Django 4.0.5 on 2022-10-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_subject_questionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='questionnaire',
            field=models.ManyToManyField(blank=True, related_name='subject_questionnaire', to='quiz.questionnaire'),
        ),
    ]
