# Generated by Django 4.0.5 on 2022-11-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_usersanswer_quiz_taker_usersanswer_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztaker',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
