# Generated by Django 4.1.3 on 2023-06-01 20:11

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bandeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='O nome da bandeira do cartão', max_length=70)),
                ('logo', models.FileField(upload_to='bandeira de cartão %Y-%m-%d')),
            ],
            options={
                'verbose_name': 'Bandeira',
                'verbose_name_plural': 'Bandeiras',
            },
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('intitucao', models.CharField(max_length=70, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('vencimento', models.DateTimeField()),
                ('limite', models.DecimalField(decimal_places=2, default=0, help_text='O Limite do cartões', max_digits=10)),
                ('bandeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandeira', to='bancos.bandeira')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_cartao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cartão',
                'verbose_name_plural': 'Cartões',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('descricao', ckeditor.fields.RichTextField()),
                ('valor', models.DecimalField(decimal_places=2, default=0, help_text='valor da compra', max_digits=10)),
                ('quantidade', models.IntegerField(default=0, help_text='quantidade', null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='O valor Total do documento', max_digits=10)),
                ('parcela', models.BooleanField(default=False, help_text='Foi parcelado')),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartao', to='bancos.cartao')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
                'ordering': ['-created'],
            },
        ),
    ]
