# Generated by Django 4.1.3 on 2023-06-02 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartao',
            old_name='intitucao',
            new_name='instituicao',
        ),
    ]
