# Generated by Django 4.1.3 on 2023-06-02 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bancos', '0002_rename_intitucao_cartao_instituicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nome_cartao', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartao',
            name='instituicao',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='cartao',
            name='nome',
            field=models.CharField(max_length=70),
        ),
    ]
