# Generated by Django 4.1.3 on 2023-06-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0003_cartao_user_alter_cartao_instituicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='numero',
            field=models.IntegerField(default=1, help_text='O numero do cartão'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
