# Generated by Django 5.1.6 on 2025-03-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_perfil_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='RiskTolerance',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='TimeHorizon',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='objective',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='preference',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='sentence',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
