# Generated by Django 5.1.6 on 2025-03-04 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_perfil_risktolerance_perfil_timehorizon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='investidor',
            field=models.ManyToManyField(blank=True, related_name='perfis', to=settings.AUTH_USER_MODEL),
        ),
    ]
