# Generated by Django 5.1.6 on 2025-03-04 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_perfil_investidor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='situacao',
            name='RiskTolerance',
            field=models.CharField(default=11, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='situacao',
            name='TimeHorizon',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='situacao',
            name='objective',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='situacao',
            name='preference',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='situacao',
            name='sentence',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='situacao',
            name='investidor',
            field=models.ManyToManyField(blank=True, related_name='situaçao', to=settings.AUTH_USER_MODEL),
        ),
    ]
