# Generated by Django 5.1.6 on 2025-03-04 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_situacao_risktolerance_situacao_timehorizon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='TimeHorizon',
            new_name='time_horizon',
        ),
        migrations.RenameField(
            model_name='situacao',
            old_name='TimeHorizon',
            new_name='time_horizon',
        ),
    ]
