# Generated by Django 5.1.6 on 2025-03-04 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_rename_timehorizon_perfil_time_horizon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='RiskTolerance',
            new_name='risk_tolerance',
        ),
        migrations.RenameField(
            model_name='situacao',
            old_name='RiskTolerance',
            new_name='risk_tolerance',
        ),
    ]
