# Generated by Django 5.1.6 on 2025-05-12 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_perfil_fixa_perfil_variável'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investidor',
            name='nome',
        ),
    ]
