# Generated by Django 4.1.3 on 2023-05-12 17:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('img', models.CharField(blank=True, max_length=17, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('descricao', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('classificacao', models.CharField(blank=True, max_length=3, null=True)),
                ('average_rating', models.CharField(blank=True, max_length=5, null=True)),
                ('average_count', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dividendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('logo', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(null=True)),
                ('descricao', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, help_text='O valor atual da ação', max_digits=10)),
                ('minimo', models.DecimalField(decimal_places=2, help_text='O valor minimo já alcançado pela ação', max_digits=10)),
                ('maximo', models.DecimalField(decimal_places=2, help_text='O valor maximo já alcançado pela ação', max_digits=10)),
                ('dividendo', models.BooleanField(default=False, help_text='A ação paga dividendos')),
                ('bonificacao', models.BooleanField(default=False, help_text='A empresa paga bonificação')),
                ('aluguel', models.BooleanField(default=False, help_text='A empresa tem ação aluguada ')),
                ('valorizacao', models.DecimalField(decimal_places=2, help_text='A valorização no perido de 12 meses', max_digits=10)),
                ('classificacao', models.CharField(blank=True, max_length=3)),
                ('average_rating', models.CharField(blank=True, max_length=5)),
                ('average_count', models.CharField(blank=True, max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_empresa_categoria', to='acoes.categoria')),
            ],
            options={
                'verbose_name': 'Empresas',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('icon', models.CharField(blank=True, max_length=40, null=True)),
                ('slug', models.SlugField(null=True)),
                ('status', models.CharField(choices=[('fundo', 'Fundo'), ('alta', 'Alta'), ('topo', 'Topo'), ('baixa', 'Baixa')], default='fundo', max_length=150)),
                ('descricao', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('classificacao', models.CharField(blank=True, max_length=3)),
                ('average_rating', models.CharField(blank=True, max_length=5)),
                ('average_count', models.CharField(blank=True, max_length=100)),
                ('empresas', models.ManyToManyField(blank=True, related_name='empresa_setor', to='acoes.empresa')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
            },
        ),
        migrations.CreateModel(
            name='SubSetor',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('img', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(null=True)),
                ('descricao', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('classificacao', models.CharField(blank=True, max_length=3)),
                ('average_rating', models.CharField(blank=True, max_length=5)),
                ('average_count', models.CharField(blank=True, max_length=100)),
                ('empresas', models.ManyToManyField(blank=True, related_name='empresa_subsetor', to='acoes.empresa')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsetor_setor', to='acoes.setor')),
            ],
            options={
                'verbose_name': 'Sub-Setor',
                'verbose_name_plural': 'Sub-Setores',
            },
        ),
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('img', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(null=True)),
                ('descricao', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('classificacao', models.CharField(blank=True, max_length=3)),
                ('average_rating', models.CharField(blank=True, max_length=5)),
                ('average_count', models.CharField(blank=True, max_length=100)),
                ('empresas', models.ManyToManyField(blank=True, related_name='empresa_segmento', to='acoes.empresa')),
                ('subsetor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmento_subsetor', to='acoes.subsetor')),
            ],
            options={
                'verbose_name': 'Segmento',
                'verbose_name_plural': 'Segmentos',
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='segmento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_segmento', to='acoes.segmento'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_setor', to='acoes.setor'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='subsetor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_subsetor', to='acoes.subsetor'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='empresas',
            field=models.ManyToManyField(blank=True, related_name='empresa_categoria', to='acoes.empresa'),
        ),
    ]
