# Generated by Django 2.2 on 2022-03-29 21:55

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import phone_field.models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$'), 'O nome de usuário só pode conter letras, digitos ou os seguintes caracteres: @/./+/-/_', 'invalid')], verbose_name='Nome de Usuário')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('address', models.CharField(blank=True, max_length=190, verbose_name='Endereço')),
                ('date_of_birth', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Estado')),
                ('status', models.CharField(choices=[('ativos', 'Ativos'), ('pendentes', 'Pendentes'), ('inativos', 'Inativos')], default='projeto', max_length=100)),
                ('city', models.CharField(blank=True, max_length=190, verbose_name='Cidade')),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Está ativo?')),
                ('is_staff', models.BooleanField(blank=True, default=False, verbose_name='É da equipe?')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('img', models.ImageField(upload_to='user')),
                ('dinheiro', models.FloatField(default=0, help_text='Valor do capital em dinheiro')),
                ('acoes', models.FloatField(default=0, help_text='Valor do capital em ações')),
                ('crypto', models.FloatField(default=0, help_text='Valor do capital em crypto moedas')),
                ('imobiliario', models.FloatField(default=0, help_text='Valor do capital em fundos imobiliario')),
                ('investimento', models.FloatField(default=0, help_text='Valor do capital investido')),
                ('retorno', models.FloatField(default=0, help_text='Valor do retorno em capital ')),
                ('balanco', models.FloatField(default=0, help_text='Valor do balanço do capital ')),
                ('capital', models.FloatField(default=0, help_text='Valor total do capital')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
