# Generated by Django 4.1.3 on 2023-05-12 17:39

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phone_field.models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$'), 'O nome de usuário só pode conter letras, digitos ou os seguintes caracteres: @/./+/-/_', 'invalid')], verbose_name='Nome de Usuário')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('address', models.CharField(blank=True, max_length=190, verbose_name='Endereço')),
                ('date_of_birth', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Estado')),
                ('status', models.CharField(choices=[('ativos', 'Ativos'), ('pendentes', 'Pendentes'), ('inativos', 'Inativos')], default='projeto', max_length=100)),
                ('city', models.CharField(blank=True, max_length=190, verbose_name='Cidade')),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Está ativo?')),
                ('is_staff', models.BooleanField(blank=True, default=False, verbose_name='É da equipe?')),
                ('situation', models.BooleanField(blank=True, default=False, verbose_name='Situação financeira')),
                ('perfil', models.BooleanField(blank=True, default=False, verbose_name='Perfil do Investidor')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('img', models.ImageField(upload_to='user')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.CharField(max_length=190, primary_key=True, serialize=False, unique=True)),
                ('condicao', models.CharField(choices=[('investidor', 'Investidor'), ('equilibrado', 'Equilibrado'), ('endividado', 'Endividado')], default='Conservador', max_length=190)),
                ('description', models.TextField()),
                ('minimum', models.IntegerField()),
                ('maximum', models.IntegerField()),
                ('usuario', models.ManyToManyField(blank=True, related_name='situacao_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.CharField(max_length=190, primary_key=True, serialize=False, unique=True)),
                ('investor', models.CharField(blank=True, choices=[('conservador', 'Conservador'), ('moderado', 'Moderado'), ('dinâmico', 'Dinâmico'), ('arrojado', 'Arrojado'), ('agressivo', 'Agressivo')], default='Conservador', max_length=190, null=True)),
                ('description', models.TextField()),
                ('risk_profile', models.CharField(max_length=150, null=True)),
                ('minimum', models.IntegerField()),
                ('maximum', models.IntegerField()),
                ('usuario', models.ManyToManyField(blank=True, related_name='perfil_investidor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacoes',
            fields=[
                ('id', models.CharField(max_length=110, primary_key=True, serialize=False)),
                ('operacao', models.CharField(choices=[('deposito', 'deposito'), ('retirada', 'retirada'), ('transferencia', 'transferencia')], default='deposito', help_text='transferência do capital', max_length=110)),
                ('tipo', models.CharField(choices=[('acoes', 'acoes'), ('crypto', 'crypto'), ('imobiliario', 'investimento'), ('forex', 'forex'), ('movimentocao', 'movimetacao')], default='acoes', help_text='O tipo da movimento', max_length=110)),
                ('data', models.DateTimeField()),
                ('descricao', models.TextField(help_text='Descrição da movimentação')),
                ('valor', models.FloatField(help_text='O valor total do usuário')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimetação_financeira', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.CharField(max_length=110, primary_key=True, serialize=False)),
                ('dinheiro', models.FloatField(default=0, help_text='Valor do capital em dinheiro')),
                ('acoes', models.FloatField(default=0, help_text='Valor do capital em ações')),
                ('crypto', models.FloatField(default=0, help_text='Valor do capital em crypto moedas')),
                ('imobiliario', models.FloatField(default=0, help_text='Valor do capital em fundos imobiliario')),
                ('forex', models.FloatField(default=0, help_text='Valor do capital em forex')),
                ('balanco', models.FloatField(default=0, help_text='Valor do balanço do capital ')),
                ('capital', models.FloatField(default=0, help_text='Valor total do capital')),
                ('retorno', models.FloatField(default=0, help_text='Valor do retorno em capital ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuário_financeiro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
