# Generated by Django 4.0.5 on 2022-11-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='perfil',
            field=models.BooleanField(blank=True, default=False, verbose_name='Perfil do Investidor'),
        ),
    ]
