# Generated by Django 4.1.3 on 2023-05-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_situacao_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='termos',
            field=models.BooleanField(default=False),
        ),
    ]
