# Generated by Django 4.0.5 on 2022-10-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_questions_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='situation',
            field=models.BooleanField(blank=True, default=False, verbose_name='Situação financeira'),
        ),
    ]
