# Generated by Django 4.0.5 on 2022-10-24 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_situation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='usuarios',
        ),
    ]
