# Generated by Django 4.1.3 on 2023-05-22 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planejamento',
            fields=[
                ('id', models.CharField(max_length=110, primary_key=True, serialize=False)),
                ('emergencia', models.FloatField(default=0, help_text='Fundo de emergência')),
                ('pms', models.FloatField(default=0, help_text='Patrimônio Mínimo de Sobrevivência')),
                ('pmr', models.FloatField(default=0, help_text='Patrimônio Mínimo Recomendado para sua Segurança')),
                ('pi', models.FloatField(default=0, help_text='Patrimônio Ideal para sua idade e situação de Consumo')),
                ('estabilidade', models.BooleanField(default=False, help_text='O tipo de empregabilidade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuário_planejamento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planejamento',
                'verbose_name_plural': 'Planejamentos',
            },
        ),
    ]
