# Generated by Django 4.0.5 on 2022-10-24 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_questions_usuarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='questionnaire',
        ),
        migrations.DeleteModel(
            name='Questionnaire',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
