# Generated by Django 4.1.3 on 2023-05-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_planejamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planejamento',
            name='emergencia',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fundo de emergência', max_digits=5),
        ),
        migrations.AlterField(
            model_name='planejamento',
            name='pi',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Patrimônio Ideal para sua idade e situação de Consumo', max_digits=5),
        ),
        migrations.AlterField(
            model_name='planejamento',
            name='pmr',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Patrimônio Mínimo Recomendado para sua Segurança', max_digits=5),
        ),
        migrations.AlterField(
            model_name='planejamento',
            name='pms',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Patrimônio Mínimo de Sobrevivência', max_digits=5),
        ),
    ]
