# Generated by Django 4.1.3 on 2023-05-22 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_planejamento_emergencia_alter_planejamento_pi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planejamento',
            name='emergencia',
        ),
    ]
