# Generated by Django 4.1.3 on 2023-05-26 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_planejamento_emergencia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Planejamento',
        ),
    ]
