# Generated by Django 4.1.3 on 2023-05-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixa', '0005_rename_tipo_categoria_status'),
        ('accounts', '0010_delete_planejamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='fixa',
            field=models.ManyToManyField(related_name='renda_fixa', to='fixa.categoria'),
        ),
    ]
