# Generated by Django 4.1.3 on 2023-05-12 17:39

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=70, unique=True)),
                ('descricao', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=70, unique=True)),
                ('descricao', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('real', models.DecimalField(decimal_places=2, max_digits=5)),
                ('previsto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('atual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('diferenca', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('variacao', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to='pessoal.categoria')),
                ('user', models.ManyToManyField(blank=True, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('real', models.DecimalField(decimal_places=2, max_digits=5)),
                ('previsto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('atual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('variacao', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='pessoal.assunto')),
                ('user', models.ManyToManyField(blank=True, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-created'],
            },
        ),
    ]
