# Generated by Django 4.1.3 on 2023-05-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0002_movimentacao_remove_despesa_assunto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacao',
            name='status',
        ),
        migrations.AddField(
            model_name='categoria',
            name='status',
            field=models.CharField(choices=[('receitas', 'Receitas'), ('despesas', 'Despesas')], default='receitas', max_length=150),
        ),
    ]
