# Generated by Django 4.1.3 on 2023-05-23 11:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0003_remove_movimentacao_status_categoria_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(default=1, max_length=70, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
