# Generated by Django 4.1.3 on 2023-05-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0005_alter_categoria_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=70),
        ),
    ]
