# Generated by Django 4.1.3 on 2023-05-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0007_remove_categoria_tipo_alter_categoria_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(default=1, max_length=90, unique=True),
            preserve_default=False,
        ),
    ]
