# Generated by Django 4.1.3 on 2023-05-24 19:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0009_alter_categoria_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacao',
            name='atual',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='diferenca',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='previsto',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='real',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='variacao',
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='descricao',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='fixa',
            field=models.BooleanField(default=1, help_text='A renda fixa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='moeda',
            field=models.CharField(default=1, help_text='A moeda para pelo serviço', max_length=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='quantidade',
            field=models.IntegerField(default=0, help_text='quantidade', null=True),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='repetir',
            field=models.BooleanField(default=1, help_text='Renda variavel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='tempo',
            field=models.IntegerField(default=0, help_text='O tempo que receberá', null=True),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, help_text='O valor Total do documento', max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='created',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='updated',
            field=models.DateTimeField(blank=True),
        ),
    ]
