# Generated by Django 4.1.3 on 2023-05-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0010_remove_movimentacao_atual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='status',
            field=models.CharField(choices=[('receitas', 'Receitas'), ('despesas', 'Despesas')], default='receitas', max_length=19),
        ),
    ]
