# Generated by Django 4.1.3 on 2023-05-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0011_movimentacao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='fixa',
            field=models.BooleanField(default=False, help_text='A renda fixa'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='repetir',
            field=models.BooleanField(default=False, help_text='Renda variavel'),
        ),
    ]
