# Generated by Django 4.1.3 on 2023-05-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0012_alter_movimentacao_fixa_alter_movimentacao_repetir'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='O valor Total do documento', max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, help_text='O valor inicial do documento', max_digits=10),
        ),
    ]
