# Generated by Django 4.1.3 on 2023-05-25 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0014_financeiro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financeiro',
            options={'ordering': ['-created'], 'verbose_name': 'Financeiro', 'verbose_name_plural': 'Financeiros'},
        ),
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'ordering': ['-created'], 'verbose_name': 'Movimentação', 'verbose_name_plural': 'Movimentações'},
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='cartao',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='despesas',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='investimento',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='receitas',
        ),
    ]
