# Generated by Django 4.1.3 on 2023-05-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0015_alter_financeiro_options_alter_movimentacao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro',
            name='cartao',
            field=models.DecimalField(decimal_places=2, default=0, help_text='O valor das despesas', max_digits=10),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='despesas',
            field=models.DecimalField(decimal_places=2, default=0, help_text='O valor das despesas', max_digits=10),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='investimento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='O valor dos cartões', max_digits=10),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='receitas',
            field=models.DecimalField(decimal_places=2, default=0, help_text='O valor das receitas', max_digits=10),
        ),
    ]
