# Generated by Django 4.1.3 on 2023-05-26 16:00

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pessoal', '0016_financeiro_cartao_financeiro_despesas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva_Emergencia_View',
            fields=[
                ('id', models.CharField(max_length=110, primary_key=True, serialize=False)),
                ('inicial', models.DecimalField(decimal_places=2, default=0, help_text='Patrimônio inicial', max_digits=10)),
                ('rendimentos', models.DecimalField(decimal_places=2, default=0, help_text='O valor redimentos', max_digits=10)),
                ('status', models.CharField(choices=[('inicial', 'Inicial'), ('excecução', 'excecução'), ('concluido', 'Concluido')], default='inicial', max_length=90)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('descricao', ckeditor.fields.RichTextField()),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='O valor Total fundo de emergência', max_digits=10)),
                ('referencia', models.DecimalField(decimal_places=2, default=0, help_text='O valor de referencia da reserva de emergência', max_digits=10)),
                ('complete_per', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='Planejamento',
            fields=[
                ('id', models.CharField(max_length=110, primary_key=True, serialize=False)),
                ('pms', models.DecimalField(decimal_places=2, default=0, help_text='Patrimônio Mínimo de Sobrevivência', max_digits=10)),
                ('pmr', models.DecimalField(decimal_places=2, default=0, help_text='Patrimônio Mínimo Recomendado para sua Segurança', max_digits=10)),
                ('pi', models.DecimalField(decimal_places=2, default=0, help_text='Patrimônio Ideal para sua idade e situação de Consumo', max_digits=10)),
                ('pnif', models.DecimalField(decimal_places=2, default=0, help_text='Patrimônio Necessário para a Independência Financeira', max_digits=10)),
                ('estabilidade', models.BooleanField(default=False, help_text='O tipo de empregabilidade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuário_planejamento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planejamento',
                'verbose_name_plural': 'Planejamentos',
            },
        ),
    ]
