# Generated by Django 4.1.3 on 2023-05-26 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pessoal', '0018_rename_reserva_emergencia_view_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuário_reserva', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
