# Generated by Django 4.1.3 on 2023-05-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0019_reserva_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('inicial', 'Inicial'), ('excecutando', 'Excecutando'), ('concluido', 'Concluido')], default='inicial', max_length=90),
        ),
    ]
