# Generated by Django 4.1.3 on 2023-05-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0020_alter_reserva_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('inicial', 'Inicial'), ('executando', 'Executando'), ('concluido', 'Concluido')], default='inicial', max_length=90),
        ),
    ]
