# Generated by Django 4.1.3 on 2023-06-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0021_alter_reserva_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro',
            name='investimento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='O valor dos investimento', max_digits=10),
        ),
    ]
