# Generated by Django 3.2.25 on 2024-03-31 18:10

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70, unique=True)),
                ('type', models.CharField(max_length=90)),
                ('icon', models.CharField(max_length=90)),
                ('iconColor', models.CharField(max_length=90)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True)),
                ('note', ckeditor.fields.RichTextField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='O valor Total do documento', max_digits=10)),
                ('recipient', models.CharField(max_length=90)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to='finance.category')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='username', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='O valor dos investimentos', max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_personal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta Bancaria',
                'verbose_name_plural': 'Conta Bancarias',
            },
        ),
    ]
