# Generated by Django 3.2.25 on 2024-03-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20240331_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Transaction',
            field=models.ManyToManyField(related_name='category_transaction', to='finance.Transaction'),
        ),
    ]
