# Generated by Django 3.2.25 on 2024-04-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_bank_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='Transaction',
            field=models.ManyToManyField(blank=True, related_name='finance_transaction', to='finance.Transaction'),
        ),
    ]
