# Generated by Django 3.2.25 on 2024-04-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_bank_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY'), ('BRL', 'BRL')], default='USD', max_length=9),
        ),
    ]
