# Generated by Django 5.1.6 on 2025-03-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
