# Generated by Django 5.1.6 on 2025-03-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_answer_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
