# Generated by Django 5.1.6 on 2025-03-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_question_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useranswer',
            options={'ordering': ['created_at'], 'verbose_name': 'User Answer', 'verbose_name_plural': 'User Answers'},
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='selected_at',
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='selected_answer',
            field=models.CharField(max_length=255),
        ),
    ]
