# Generated by Django 4.1.3 on 2023-05-30 01:15

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome do Produto', max_length=90)),
                ('descricao', ckeditor.fields.RichTextField(help_text='descrição do produto')),
                ('percent', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('active', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Renda',
            fields=[
                ('id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('instituicao', models.CharField(help_text='Nome da instituição financeira', max_length=90)),
                ('status', models.CharField(choices=[('banco', 'Banco'), ('corretora', 'Corretora')], default='banco', max_length=90)),
                ('tipo', models.CharField(choices=[('banco', 'Banco'), ('corretora', 'Corretora')], default='banco', max_length=90)),
                ('moeda', models.CharField(help_text='A moeda do investimento', max_length=19)),
                ('created', models.DateTimeField(blank=True)),
                ('updated', models.DateTimeField(blank=True)),
                ('carencia', models.IntegerField(default=0, help_text='O tempo que receberá', null=True)),
                ('diaria', models.BooleanField(default=False, help_text='Liquidez diária')),
                ('imposto', models.BooleanField(default=False, help_text='Imposto de renda ')),
                ('taxa', models.BooleanField(default=False, help_text='Taxas de administração')),
                ('iof', models.BooleanField(default=False, help_text='Imposto sobre Operações Financeiras (IOF)')),
                ('fgc', models.BooleanField(default=False, help_text='Garantia do Fundo Garantidor de Crédito (FGC)')),
                ('rentabilidade', models.BooleanField(default=False, help_text='Rentabilidade baixa')),
                ('minimo', models.DecimalField(decimal_places=2, default=0, help_text='O valor Minimo de deposito', max_digits=10)),
                ('percent', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('active', models.BooleanField()),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to='fixa.categoria')),
            ],
            options={
                'verbose_name': 'Renda Fixa',
                'verbose_name_plural': 'Rendas Fixas',
            },
        ),
    ]
