# Generated by Django 4.1.3 on 2023-05-30 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='renda',
            name='pos',
            field=models.BooleanField(default=False, help_text='Rendimento é definido depois'),
        ),
        migrations.AddField(
            model_name='renda',
            name='pre',
            field=models.BooleanField(default=False, help_text='Taxa pré-fixada (fixada antes)'),
        ),
    ]
