# Generated by Django 4.1.3 on 2023-05-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixa', '0003_alter_categoria_percent_alter_renda_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renda',
            name='tipo',
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('público', 'Público'), ('privado', 'Privado')], default='banco', max_length=90),
        ),
    ]
