# Generated by Django 4.1.3 on 2023-05-30 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixa', '0004_remove_renda_tipo_categoria_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='tipo',
            new_name='status',
        ),
    ]
