# Generated by Django 4.1.3 on 2023-05-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixa', '0005_rename_tipo_categoria_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='renda',
            name='basileia',
            field=models.FloatField(default=0, help_text='índice da saúde financeira de uma instituição financeira'),
        ),
        migrations.AddField(
            model_name='renda',
            name='logo',
            field=models.ImageField(default=1, upload_to='logo/% Y/% m/% d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='renda',
            name='mobilizacao',
            field=models.FloatField(default=1, help_text='índice em ativos imobilizados como imóveis e veículos'),
            preserve_default=False,
        ),
    ]
