# Generated by Django 4.1.3 on 2023-05-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixa', '0006_renda_basileia_renda_logo_renda_mobilizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renda',
            name='logo',
            field=models.ImageField(upload_to='logo/%Y/%m/%d/'),
        ),
    ]
