# Generated by Django 4.1.3 on 2023-05-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixa', '0007_alter_renda_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='renda',
            name='risco',
            field=models.CharField(choices=[('excelente', 'Excelente'), ('bom', 'Bom'), ('medio', 'Medio'), ('pessimo', 'Pessimo')], default='medio', max_length=90),
        ),
    ]
