# Generated by Django 4.1.3 on 2023-05-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixa', '0008_renda_risco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renda',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='renda',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
