# Generated by Django 4.1.3 on 2023-05-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixa', '0009_alter_renda_created_alter_renda_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renda',
            name='logo',
            field=models.CharField(max_length=700),
        ),
    ]
