# Generated by Django 5.1.6 on 2025-03-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commoditie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='image')),
                ('yahoo', models.CharField(max_length=255)),
                ('tradingview', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='Flags')),
                ('yahoo', models.CharField(max_length=255)),
                ('tradingview', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='image/flags')),
                ('yahoo', models.CharField(max_length=255)),
                ('tradingview', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='logo')),
                ('yahoo', models.CharField(max_length=255)),
                ('tradingview', models.CharField(max_length=255)),
            ],
        ),
    ]
