# Generated by Django 5.1.6 on 2025-03-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Ação', 'verbose_name_plural': 'Ações'},
        ),
        migrations.AddField(
            model_name='stock',
            name='category',
            field=models.CharField(choices=[('Tecnologia da Informação', 'Tecnologia da Informação'), ('Saúde', 'Saúde'), ('Financeiro', 'Financeiro'), ('Consumo Discricionário', 'Consumo Discricionário'), ('Consumo Básico', 'Consumo Básico'), ('Indústria', 'Indústria'), ('Energia', 'Energia'), ('Materiais', 'Materiais'), ('Serviços de Utilidade Pública', 'Serviços de Utilidade Pública'), ('Imobiliário', 'Imobiliário'), ('Comunicação', 'Comunicação')], default='Tecnologia da Informação', max_length=50, verbose_name='Categoria'),
        ),
    ]
