# Generated by Django 5.1.6 on 2025-03-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_alter_stock_options_stock_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='status',
            field=models.CharField(choices=[('Maior', 'Maior'), ('Menor', 'Menor'), ('Exotico', 'Exotico')], default='Maior', max_length=10),
        ),
    ]
