# Generated by Django 5.1.6 on 2025-04-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_currency_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='Flags'),
        ),
    ]
