# Generated by Django 5.1.6 on 2025-04-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_alter_currency_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='tradingview',
            new_name='exchange',
        ),
        migrations.AddField(
            model_name='stock',
            name='mt5',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
