# Generated by Django 5.1.6 on 2025-04-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_rename_tradingview_stock_exchange_stock_mt5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
    ]
