# Generated by Django 5.1.6 on 2025-04-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_alter_stock_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='mt5',
        ),
    ]
