# Generated by Django 5.1.6 on 2025-04-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_remove_stock_mt5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='yahoo',
        ),
    ]
