# Generated by Django 5.1.6 on 2025-04-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_remove_stock_yahoo'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='mt5',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
