# Generated by Django 5.1.6 on 2025-04-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_stock_mt5'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='signal_1d',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='signal_1w',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='signal_4h',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
