# Generated by Django 4.2 on 2024-12-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
