# Generated by Django 4.2 on 2024-12-18 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_subscriber_delete_newsletter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['-created'], 'verbose_name': 'Assinante', 'verbose_name_plural': 'Assinantes'},
        ),
        migrations.RenameField(
            model_name='subscriber',
            old_name='subscriber',
            new_name='subscribed',
        ),
    ]
