# Generated by Django 3.2.25 on 2024-04-21 14:49

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70, unique=True)),
                ('despesas', models.ManyToManyField(blank=True, to='personal.Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.CharField(max_length=110, primary_key=True, serialize=False)),
                ('inicial', models.DecimalField(decimal_places=2, default=0, help_text='Patrimônio inicial', max_digits=10)),
                ('rendimentos', models.DecimalField(decimal_places=2, default=0, help_text='O valor redimentos', max_digits=10)),
                ('status', models.CharField(choices=[('inicial', 'Inicial'), ('executando', 'Executando'), ('concluido', 'Concluido')], default='inicial', max_length=90)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('descricao', ckeditor.fields.RichTextField()),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='O valor Total fundo de emergência', max_digits=10)),
                ('referencia', models.DecimalField(decimal_places=2, default=0, help_text='O valor de referencia da reserva de emergência', max_digits=10)),
                ('complete_per', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuário_reserva', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='Planejamento',
            fields=[
                ('id', models.CharField(max_length=110, primary_key=True, serialize=False)),
                ('pms', models.DecimalField(decimal_places=2, default=0, help_text='Patrimônio Mínimo de Sobrevivência', max_digits=10)),
                ('pmr', models.DecimalField(decimal_places=2, default=0, help_text='Patrimônio Mínimo Recomendado para sua Segurança', max_digits=10)),
                ('pi', models.DecimalField(decimal_places=2, default=0, help_text='Patrimônio Ideal para sua idade e situação de Consumo', max_digits=10)),
                ('pnif', models.DecimalField(decimal_places=2, default=0, help_text='Patrimônio Necessário para a Independência Financeira', max_digits=10)),
                ('estabilidade', models.BooleanField(default=False, help_text='O tipo de empregabilidade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuário_planejamento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planejamento',
                'verbose_name_plural': 'Planejamentos',
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('receitas', 'Receitas'), ('despesas', 'Despesas')], default='receitas', max_length=19)),
                ('created', models.DateTimeField(blank=True)),
                ('updated', models.DateTimeField(blank=True)),
                ('descricao', ckeditor.fields.RichTextField()),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='O valor Total do documento', max_digits=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to='personal.categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('receitas', models.DecimalField(decimal_places=2, default=0, help_text='O valor das receitas', max_digits=10)),
                ('despesas', models.DecimalField(decimal_places=2, default=0, help_text='O valor das despesas', max_digits=10)),
                ('cartao', models.DecimalField(decimal_places=2, default=0, help_text='O valor das despesas', max_digits=10)),
                ('investimento', models.DecimalField(decimal_places=2, default=0, help_text='O valor dos investimento', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='O valor dos investimentos', max_digits=10)),
                ('user', models.ManyToManyField(blank=True, related_name='financeiro_pessoal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financeiro',
                'verbose_name_plural': 'Financeiros',
                'ordering': ['-created'],
            },
        ),
    ]
