# Generated by Django 5.1.6 on 2025-05-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
    ]
