# Generated by Django 3.2.25 on 2024-04-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='punctuation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('Casa', 'Casa'), ('Alimentação', 'Alimentação'), ('Transporte', 'Transporte'), ('Ssaúde', 'Saúde'), ('Lazer', 'Lazer')], default='receitas', max_length=150),
        ),
    ]
