# Generated by Django 3.2.25 on 2024-04-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20240421_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='status',
            field=models.CharField(choices=[('Fixa', 'Fixa'), ('Variavel', 'Variavel')], default='Fixa', max_length=150),
        ),
    ]
