# Generated by Django 3.2.25 on 2024-04-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_categoria_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='status',
            field=models.CharField(choices=[('Fixa', 'Fixa'), ('Variavel', 'Variavel')], default='Fixas', max_length=150),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('Casa', 'Casa'), ('Alimentação', 'Alimentação'), ('Financeiro', 'Financeiro'), ('Transporte', 'Transporte'), ('Ssaúde', 'Saúde'), ('Lazer', 'Lazer')], default='receitas', max_length=150),
        ),
    ]
