# Generated by Django 3.2.25 on 2024-04-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20240421_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='status',
            field=models.CharField(choices=[('Fixa', 'Fixa'), ('Variavel', 'Variavel'), ('Extra', 'Extra'), ('Adicionais', 'Adicionais')], default='Fixas', max_length=150),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('Habitação', 'Habitação'), ('Transporte', 'Transporte'), ('Alimentação', 'Alimentação'), ('Saúde', 'Saúde'), ('Educação', 'Educação'), ('Impostos', 'Impostos'), ('Cuidados pessoais', 'Cuidados pessoais'), ('Manutenção/ prevenção', 'Manutenção/ prevenção'), ('Transporte', 'Transporte'), ('Vestuario', 'Vestuario'), ('Lazer', 'Lazer'), ('Outros', 'Outros')], default='receitas', max_length=150),
        ),
    ]
