# Generated by Django 3.2.25 on 2024-04-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_auto_20240421_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='despesas',
            field=models.ManyToManyField(blank=True, related_name='despesas', to='personal.Movimentacao'),
        ),
    ]
