# Generated by Django 3.2.25 on 2024-04-21 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_alter_categoria_despesas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='despesas',
        ),
    ]
