# Generated by Django 3.2.25 on 2024-04-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_remove_categoria_despesas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=70),
        ),
    ]
