# Generated by Django 3.2.25 on 2024-04-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_alter_categoria_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
