# Generated by Django 3.2.25 on 2024-04-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0010_auto_20240421_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='status',
            field=models.CharField(choices=[('Receitas', 'Receitas'), ('Despesas', 'Despesas')], default='receitas', max_length=19),
        ),
    ]
