# Generated by Django 3.2.25 on 2024-04-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0011_alter_movimentacao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='total',
            field=models.FloatField(default=0, help_text='O valor Total do documento'),
        ),
    ]
