# Generated by Django 3.2.25 on 2024-04-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0017_alter_categoria_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('Renda', 'Renda'), ('Habitação', 'Habitação'), ('Transporte', 'Transporte'), ('Alimentação', 'Alimentação'), ('Saúde', 'Saúde'), ('Educação', 'Educação'), ('Impostos', 'Impostos'), ('Cuidados pessoais', 'Cuidados pessoais'), ('Manutenção/ prevenção', 'Manutenção/ prevenção'), ('Poupanças ou Investimentos', 'Poupanças ou Investimentos'), ('Presente ou Doação', 'Presente ou Doação'), ('Assessoria Jurídica', 'Assessoria Jurídica'), ('Transporte', 'Transporte'), ('Vestuario', 'Vestuario'), ('Lazer', 'Lazer'), ('Emprestimos', 'Emprestimos'), ('Seguro', 'Seguro'), ('Animais de Estimação', 'Animais de Estimação'), ('Outros', 'Outros')], default='receitas', max_length=150),
        ),
    ]
