# Generated by Django 3.2.25 on 2024-04-22 19:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal', '0018_alter_categoria_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('revenues', models.DecimalField(decimal_places=2, default=0, help_text='O valor das receitas', max_digits=10)),
                ('expenses', models.DecimalField(decimal_places=2, default=0, help_text='O valor das despesas', max_digits=10)),
                ('last', models.DecimalField(decimal_places=2, default=0, help_text='O valor das despesas', max_digits=10)),
                ('percent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='O valor dos investimentos', max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financeiro_pessoal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financeiro',
                'verbose_name_plural': 'Financeiros',
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='Financeiro',
        ),
    ]
