# Generated by Django 3.2.25 on 2024-04-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0020_auto_20240422_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='spending',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Limite de gastos', max_digits=10),
        ),
    ]
