# Generated by Django 3.2.25 on 2024-04-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0021_periodo_spending'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='movimentacao',
            field=models.ManyToManyField(related_name='movimentacao_despesas', to='personal.Movimentacao'),
        ),
    ]
