# Generated by Django 3.2.25 on 2024-04-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0025_plano'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plano',
        ),
    ]
