# Generated by Django 3.2.25 on 2024-04-24 00:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0027_plano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='total',
        ),
        migrations.AddField(
            model_name='plano',
            name='economia',
            field=models.DecimalField(decimal_places=2, default=0, help_text='O valor mensal economizado ', max_digits=10),
        ),
        migrations.AddField(
            model_name='plano',
            name='meta',
            field=models.DecimalField(decimal_places=2, default=0, help_text='O valor Total da meta', max_digits=10),
        ),
        migrations.AddField(
            model_name='plano',
            name='percent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='plano',
            name='quantia',
            field=models.DecimalField(decimal_places=2, default=0, help_text='A quantia total adquirida', max_digits=10),
        ),
    ]
