# Generated by Django 3.2.25 on 2024-04-24 14:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0028_auto_20240423_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('meta', models.DecimalField(decimal_places=2, default=0, help_text='A quantia total adquirida', max_digits=10)),
                ('percent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('quantia', models.DecimalField(decimal_places=2, default=0, help_text='A quantia total adquirida', max_digits=10)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quanti_plano', to='personal.plano')),
            ],
            options={
                'verbose_name': 'Quantia',
                'verbose_name_plural': 'Quantias',
            },
        ),
    ]
