# Generated by Django 5.1.6 on 2025-03-31 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('asset', models.CharField(max_length=60)),
                ('entry', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('sell', 'sell'), ('buy', 'buy')], default='buy', max_length=20)),
                ('volume', models.FloatField()),
                ('price_entry', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_departure', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stoploss', models.BooleanField(default=False)),
                ('takeprofit', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
