# Generated by Django 5.1.6 on 2025-04-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='maic',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='operation',
            name='type',
            field=models.CharField(choices=[(0, 'sell'), (1, 'buy')], default=1, max_length=20),
        ),
    ]
