# Generated by Django 5.1.6 on 2025-04-15 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_operation_comment_operation_maic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='maic',
            new_name='magic',
        ),
    ]
