# Generated by Django 5.1.6 on 2025-04-16 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_rename_maic_operation_magic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='entry',
            new_name='date',
        ),
    ]
