# Generated by Django 2.2 on 2022-03-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='forks',
            field=models.IntegerField(blank=True, default=0, help_text='copia de sistema', null=True),
        ),
    ]
