# Generated by Django 2.2 on 2022-03-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_historico_forks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='id',
            field=models.CharField(help_text='codigo de indentificação do ativo', max_length=150, primary_key=True, serialize=False),
        ),
    ]
