# Generated by Django 5.1.6 on 2025-04-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robo',
            name='logo',
        ),
    ]
