# Generated by Django 5.1.6 on 2025-04-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0002_remove_robo_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.IntegerField(choices=[(1, 'Conservador'), (2, 'Conservador'), (3, 'Agressivo'), (4, 'Ultra Agressivo')], unique=True)),
                ('profile', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('stock', models.IntegerField(default=0)),
                ('crypto', models.IntegerField(default=0)),
                ('forex', models.IntegerField(default=0)),
                ('commodities', models.IntegerField(default=0)),
            ],
        ),
    ]
