# Generated by Django 5.1.6 on 2025-04-15 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0003_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='advisor',
            field=models.ForeignKey(default=1, help_text='O orientador associado a este nível de risco.', on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='advisors.robo', verbose_name='Orientador'),
            preserve_default=False,
        ),
    ]
