# Generated by Django 5.1.6 on 2025-04-15 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0005_alter_level_risk_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='description',
        ),
    ]
