# Generated by Django 5.1.6 on 2025-04-15 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0006_remove_level_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='profile',
        ),
    ]
