# Generated by Django 5.1.6 on 2025-04-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0007_remove_level_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alocation', models.DecimalField(decimal_places=2, max_digits=5)),
                ('advisor', models.ManyToManyField(related_name='assets', to='advisors.robo')),
            ],
        ),
    ]
