# Generated by Django 5.1.6 on 2025-04-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0008_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='alocation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
