# Generated by Django 5.1.6 on 2025-04-15 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0009_alter_asset_alocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='robo',
            name='asset',
            field=models.ForeignKey(default=1, help_text='O ativo financeiro associado a este robô.', on_delete=django.db.models.deletion.CASCADE, related_name='robots', to='advisors.asset'),
            preserve_default=False,
        ),
    ]
