# Generated by Django 5.1.6 on 2025-04-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0010_robo_asset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': 'Ativo', 'verbose_name_plural': 'Ativos'},
        ),
        migrations.AlterField(
            model_name='asset',
            name='advisor',
            field=models.ManyToManyField(blank=True, related_name='assets', to='advisors.robo'),
        ),
    ]
