# Generated by Django 5.1.6 on 2025-04-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0011_alter_asset_options_alter_asset_advisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='alocation',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
