# Generated by Django 5.1.6 on 2025-04-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0012_alter_asset_alocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='risk_level',
            field=models.IntegerField(choices=[(1, 'Conservador'), (3, 'Moderado'), (2, 'Agressivo'), (4, 'Ultra Agressivo')], unique=True),
        ),
    ]
