# Generated by Django 5.1.6 on 2025-04-17 21:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0013_alter_level_risk_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, help_text='Quantidade de operações ou contratos.', validators=[django.core.validators.MinValueValidator(1)])),
                ('level', models.FloatField(default=0.01, help_text='Percentual de risco por operação (0.0 a 1.0).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('breakeven', models.IntegerField(default=0, help_text='Ponto de equilíbrio da operação em pontos ou unidades específicas.')),
                ('advisor', models.ForeignKey(help_text='Robô responsável pela operação.', on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='advisors.robo')),
            ],
            options={
                'verbose_name': 'Configuração de Risco',
                'verbose_name_plural': 'Configurações de Risco',
                'ordering': ['advisor'],
            },
        ),
    ]
