# Generated by Django 5.1.6 on 2025-04-17 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0014_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='amount',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade de operações ou contratos.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='risk',
            name='level',
            field=models.FloatField(default=0.0, help_text='Percentual de risco por operação (0.0 a 1.0).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
