# Generated by Django 5.1.6 on 2025-04-17 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0015_alter_risk_amount_alter_risk_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='amount',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade de operações ou contratos.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
