# Generated by Django 5.1.6 on 2025-05-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0016_alter_risk_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robo',
            name='asset',
        ),
        migrations.AddField(
            model_name='robo',
            name='asset',
            field=models.ManyToManyField(help_text='O ativo financeiro associado a este robô.', related_name='robots', to='advisors.asset'),
        ),
    ]
